SELECT s.ADDRESS FROM STUDIO as s
WHERE s.NAME = 'MGM'

SELECT ms.BIRTHDATE FROM MOVIESTAR as ms
WHERE ms.NAME = 'Sandra Bullock'

SELECT si.STARNAME FROM STARSIN as si
WHERE si.MOVIEYEAR = 1980 AND si.MOVIETITLE LIKE '%Empire%'

SELECT me.NAME FROM MOVIEEXEC as me
WHERE me.NETWORTH > 10000000

SELECT ms.NAME FROM MOVIESTAR as ms
WHERE ms.GENDER = 'M' OR ms.ADDRESS = 'Prefect Rd.'