SELECT NAME 
FROM MOVIESTAR AS ms
JOIN STARSIN AS si 
	ON ms.NAME = si.STARNAME
WHERE 
	si.MOVIETITLE = 'Terms of Endearment' AND 
	ms.GENDER = 'M'

SELECT NAME 
FROM MOVIESTAR AS ms
JOIN STARSIN AS si 
	ON ms.NAME = si.STARNAME
JOIN MOVIE AS m
	ON si.MOVIETITLE = m.TITLE
WHERE 
	m.STUDIONAME = 'MGM' AND
	m.YEAR = 1995

SELECT DISTINCT NAME 
FROM MOVIEEXEC AS me
JOIN MOVIE AS m
	ON me.CERT# = m.PRODUCERC#
WHERE 
	m.STUDIONAME = 'MGM'

SELECT TITLE
FROM MOVIE AS m
WHERE m.LENGTH > (
	SELECT TOP(1) LENGTH 
	FROM MOVIE 
	WHERE MOVIE.TITLE = 'Star Wars'
)

SELECT NAME
FROM MOVIEEXEC AS me
WHERE me.NETWORTH > (
	SELECT TOP(1) NETWORTH 
	FROM MOVIEEXEC 
	WHERE MOVIEEXEC.NAME = 'Merv Griffin'
)

SELECT TITLE 
FROM MOVIE AS m
WHERE m.PRODUCERC# IN (
	SELECT CERT#
	FROM MOVIEEXEC AS me
	WHERE me.NETWORTH > (
		SELECT TOP(1) NETWORTH 
		FROM MOVIEEXEC 
		WHERE MOVIEEXEC.NAME = 'Merv Griffin'
	)
)

