CREATE DATABASE Company

CREATE TABLE Locations (
	Id INT NOT NULL PRIMARY KEY,
	City NVARCHAR(50),
	Address NVARCHAR(50),
)

CREATE TABLE Depts (
	Id INT NOT NULL PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
)

CREATE TABLE Projects (
	Id INT NOT NULL PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	LocationId INT FOREIGN KEY REFERENCES Locations(Id)
)

CREATE TABLE Employees (
	SSN NVARCHAR(10) NOT NULL PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	BirthDate DATE,
	Address NVARCHAR(50),
	Salary DECIMAL(18,2),
	DeptId INT FOREIGN KEY REFERENCES Depts(Id)
)

CREATE TABLE ProjectEmployees
(
	EmployeeId NVARCHAR(10),
	ProjectId INT,
	CONSTRAINT ProjectEmployeesPk PRIMARY KEY (EmployeeId, ProjectId),
	CONSTRAINT FK_Employee
      FOREIGN KEY (EmployeeId) REFERENCES Employees (SSN),
	CONSTRAINT FK_Project
      FOREIGN KEY (ProjectId) REFERENCES Projects (Id)
)

ALTER TABLE Depts
ADD ManagerId NVARCHAR(10) FOREIGN KEY REFERENCES Employees (SSN)