CREATE DATABASE BiocosmeticsShop

CREATE TABLE Categories (
	Id INT NOT NULL PRIMARY KEY,
	Name NVARCHAR(30) NOT NULL
)

CREATE TABLE Products (
	Id INT NOT NULL PRIMARY KEY,
	Name NVARCHAR(30) NOT NULL,
	Description NVARCHAR(MAX) NOT NULL,
	Price DECIMAL(18, 2) NOT NULL,
	Quantity INT NOT NULL,
	CategoryId INT NOT NULL FOREIGN KEY REFERENCES Categories(Id)
)

CREATE TABLE Roles (
	Id INT NOT NULL PRIMARY KEY,
	Name NVARCHAR(30) NOT NULL
)

CREATE TABLE Users (
	Id INT NOT NULL PRIMARY KEY,
	Name NVARCHAR(30) NOT NULL,
	RoleId INT NOT NULL FOREIGN KEY REFERENCES Roles(Id)
)

CREATE TABLE Comments (
	Id INT NOT NULL PRIMARY KEY,
	Content NVARCHAR(MAX) NOT NULL,
	AuthorId INT NOT NULL FOREIGN KEY REFERENCES Users(Id),
	ParentCommentId INT FOREIGN KEY REFERENCES Comments(Id)
)

CREATE TABLE Orders
(
	ProductId INT,
	UserId INT,
	CONSTRAINT OrdersPk PRIMARY KEY (ProductId, UserId),
	CONSTRAINT FK_Products
      FOREIGN KEY (ProductId) REFERENCES Products (Id),
	CONSTRAINT FK_Users
      FOREIGN KEY (UserId) REFERENCES Users (Id)
)