CREATE DATABASE FlightSystem

USE FlightSystem

CREATE TABLE Airlines (
	Code CHAR(2) NOT NULL PRIMARY KEY,
	Name VARCHAR(20) UNIQUE NOT NULL,
	Country VARCHAR(50) NOT NULL
)

CREATE TABLE Airports (
	Code CHAR(3) NOT NULL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Country VARCHAR(50) NOT NULL,
	City VARCHAR(50) NOT NULL
)

CREATE Table Airplanes (
	Code CHAR(3) NOT NULL PRIMARY KEY,
	Type VARCHAR(30) NOT NULL,
	Seats INT NOT NULL CHECK (Seats > 0),
	Year INT NOT NULL,
)

CREATE TABLE Flights (
	FNumber CHAR(10) NOT NULL PRIMARY KEY,
	AirlineOperator CHAR(2) NOT NULL FOREIGN KEY REFERENCES Airlines(Code),
	DepAirport CHAR(3) NOT NULL FOREIGN KEY REFERENCES Airports(Code),
	ArrAirport CHAR(3) NOT NULL FOREIGN KEY REFERENCES Airports(Code),
	FlightTime TIME NOT NULL,
	FlightDuration INT NOT NULL CHECK (FlightDuration > 0),
	Airplane CHAR(3) NOT NULL FOREIGN KEY REFERENCES Airplanes(Code)
)

CREATE TABLE Customers (
	Id INT NOT NULL PRIMARY KEY,
	FName VARCHAR(50) NOT NULL,
	LName VARCHAR(50) NOT NULL,
	Email VARCHAR(50)
)

CREATE TABLE Agencies (
	NAME VARCHAR(100) NOT NULL PRIMARY KEY,
	Country VARCHAR(50) NOT NULL,
	City VARCHAR(50) NOT NULL,
	Phone VARCHAR(50)
)

CREATE TABLE Bookings (
	Code CHAR(6) NOT NULL PRIMARY KEY,
	Agency VARCHAR(100) NOT NULL FOREIGN KEY REFERENCES Agencies(Name),
	AirlineCode CHAR(2) NOT NULL FOREIGN KEY REFERENCES Airlines(Code),
	FlightNumber CHAR(10) NOT NULL FOREIGN KEY REFERENCES Flights(FNumber),
	CustomerId INT NOT NULL FOREIGN KEY REFERENCES Customers(Id),
	BookingDate DATE NOT NULL,
	FlightDate DATE NOT NULL,
	Price DECIMAL(9,2) NOT NULL,
	Status BIT NOT NULL
)