CREATE DATABASE ShopSystem

USE ShopSystem

CREATE TABLE Cities (
	Id INT NOT NULL PRIMARY KEY,
	Name NVARCHAR(20) NOT NULL,
	Area NVARCHAR(20) NOT NULL,
	Municipality NVARCHAR(20) NOT NULL
)

CREATE TABLE ProductTypes (
	Id INT NOT NULL PRIMARY KEY,
	Name NVARCHAR(20) NOT NULL,
)

CREATE TABLE Products (
	Id INT NOT NULL PRIMARY KEY,
	Name NVARCHAR(20) NOT NULL,
	Price DECIMAL(9,2) NOT NULL,
	TypeId INT NOT NULL FOREIGN KEY REFERENCES ProductTypes(Id)
)

CREATE TABLE Clients (
	Id INT NOT NULL PRIMARY KEY,
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	EGN CHAR(10) NOT NULL,
	CityId INT NOT NULL FOREIGN KEY REFERENCES Cities(Id)
)

CREATE TABLE Sales (
	Id INT NOT NULL PRIMARY KEY,
	Date DATE NOT NULL,
	ClientId INT NOT NULL FOREIGN KEY REFERENCES Clients(Id),
	PaymentType NVARCHAR(20) NOT NULL
)

CREATE TABLE SoldProducts (
	SaleId INT NOT NULL FOREIGN KEY REFERENCES Sales(Id),
	ProductId INT NOT NULL FOREIGN KEY REFERENCES Products(Id),
	Quantity INT NOT NULL,
	PRIMARY KEY (SaleId, ProductId)
)

