SELECT Studioname, COUNT(Studioname) as count
FROM MOVIE
GROUP BY Studioname
ORDER BY STUDIONAME 

SELECT TITLE FROM MOVIE
JOIn MOVIEEXEC on movie.PRODUCERC# = MOVIEEXEC.CERT#
WHERE MOVIEEXEC.ADDRESS like '%Rd%'

SELECT distinct movie.TITLE, MOVIEEXEC.NAME
FROM movie
JOIN starsin on movie.TITLE = STARSIN.MOVIETITLE
JOIN MOVIEEXEC on movie.PRODUCERC# = MOVIEEXEC.CERT#
JOIN MOVIESTAR on STARSIN.STARNAME = MOVIESTAR.NAME
WHERE YEAR(MOVIESTAR.BIRTHDATE) >= 1950

